apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: arm64v8/mysql:8.0 # mysql:5.7replace if needed
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "your_password"
            - name: MYSQL_DATABASE
              value: "todo_db"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "password"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  selector:
    matchLabels:
      app: fastapi
  replicas: 1
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: hfmartinez/fastapi-todo-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          # envFrom:
          #   - configMapRef:
          #       name: fastapi-config
          #   - secretRef:
          #       name: fastapi-secrets
          env:
            - name: DATABASE_HOST
              value: "mysql"
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_DATABASE
              value: todo_db
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: fastapi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
data:
  DATABASE_HOST: "mysql"
  MYSQL_DATABASE: "todo_db"
  MYSQL_USER: "user"

---
apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root_password"
  MYSQL_PASSWORD: "password"
