name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build FastApi and push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-crud:latest \
            --push .
  
